export const FolderTypes = {
  COMPONENTS: "COMPONENTS-FOLDER",
  ATTRIBUTE_FOLDER: "ATTRIBUTES-FOLDER",
  ENUM_FOLDER: "ENUM-FOLDER",
  TAGS_FOLDER: "TAGS-FOLDER",
  FLOW_FOLDER: "FLOW-FOLDER",
  EXAMPLE_FOLDER: "EXAMPLE-FOLDER",
  TLC_FOLDER: "TLC-FOLDER",
};
