export const FolderTypes = {
  COMPONENTS: "COMPONENTS-FOLDER",
  ATTRIBUTE_FOLDER: "ATTRIBUTE_FOLDER",
  ENUM_FOLDER: "ENUM_FOLDER",
  TAGS_FOLDER: "TAG_FOLDER",
  FLOW_FOLDER: "FLOW_FOLDER",
  EXAMPLE_FOLDER: "EXAMPLE_FOLDER",
  TLC_FOLDER: "TLC_FOLDER",
};
